### ISSUE TITLE
invalid conversion '% ~' to 'format'

### ISSUE THREAD

**Issue by nitrou5** [Qbox-project/qbx_weed#22]
### Summary

@qbx_weed/client/main.lua:53: invalid conversion '% ~' to 'format'

### Reproduction

1. Go inside a house
2. Try to plant seed
3. See error in console: @qbx_weed/client/main.lua:53: invalid conversion '% ~' to 'format'

### Expected behavior

Weed should be planted so Everyone should be high and happy

### Actual behavior

Weed not planting possible shortage of weed in the city

### Current Version

latest

### Custom Resources

n/a

**Comment by solareon** [comment]
https://github.com/Qbox-project/qbx_weed/blob/295f470c4a6b8a4b5f38f030e79eb65cf6bad298/client/main.lua#L53

should be
```lua
local label = ('~g~%s~w~ [%s] | %s ~b~%s% ~w~ | %s ~b~%s~w~'):format(locale('text.sort'), sharedConfig.plants[v.sort].label, gender, locale('text.nutrition'), v.food, locale('text.health'), v.health)
```

Can you try this @nitrou5 ?

**Comment by nitrou5** [comment]
> https://github.com/Qbox-project/qbx_weed/blob/295f470c4a6b8a4b5f38f030e79eb65cf6bad298/client/main.lua#L53
> 
> should be
> 
> ```lua
> local label = ('~g~%s~w~ [%s] | %s ~b~%s% ~w~ | %s ~b~%s~w~'):format(locale('text.sort'), sharedConfig.plants[v.sort].label, gender, locale('text.nutrition'), v.food, locale('text.health'), v.health)
> ```
> 
> Can you try this @nitrou5 ?

:thumbsup:
