### ISSUE TITLE
[BUG]SCRIPT ERROR: @qb-weed/server/main.lua:56

### ISSUE THREAD

**Issue by ghost** [Qbox-project/qbx_weed#7]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to 'start the server'
2. Click on 'nothing'
4. See the error

**Expected behavior**
Not to see the error

**Screenshots**
![image](https://user-images.githubusercontent.com/64894726/224461410-2ac4ef6b-ad74-456e-b0b6-7a0150bfcabe.png)

**Questions (please complete the following information):**
 - When you last updated: [just now]
 - Are you using custom resource? which ones? [none]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**
No

**Comment by YvanCywan** [comment]
#6 was made a few days ago to fix this error
